"""
Project mental model generator for elephant-coder.

Generates a human-readable project overview from indexed memories
and the file link graph. Injected into Claude's context at session start.

Fully Redis-backed. Slow operations (git log, framework detection) run in a
background daemon thread and cache results — project_overview never blocks.
"""

import logging
import subprocess
import threading
from pathlib import Path

logger = logging.getLogger("elephant-coder.mental_model")

# Background cache — populated by daemon thread, read by project_overview
_cache: dict[str, str] = {}
_cache_lock = threading.Lock()


def warm_cache(project_root: str) -> None:
    """Start a daemon thread to populate git/framework cache. Non-blocking."""
    def _worker():
        try:
            _cache["recent_changes"] = _git_recent_changes(project_root)
        except Exception:
            _cache["recent_changes"] = ""
        try:
            from framework_detector import detect_frameworks
            frameworks = detect_frameworks(project_root)
            if frameworks:
                parts = ["### Detected Frameworks", ""]
                for fw in frameworks:
                    line = f"- **{fw['name']}** ({fw['detected_as']})"
                    if fw.get("github"):
                        line += f" — {fw['github']}"
                    parts.append(line)
                parts.append("")
                _cache["frameworks"] = "\n".join(parts)
            else:
                _cache["frameworks"] = ""
        except Exception:
            _cache["frameworks"] = ""
        logger.info("Background cache warmed for %s", project_root)

    t = threading.Thread(target=_worker, daemon=True)
    t.start()


def generate_mental_model(store, project_root: str) -> str:
    """Generate a project mental model from indexed memories + link graph."""
    lines = ["## Project Mental Model (auto-generated by elephant-coder)", ""]
    _add_project_identity(store, project_root, lines)
    _add_class_overview(store, project_root, lines)

    # Append cached background results (non-blocking — uses whatever is ready)
    with _cache_lock:
        rc = _cache.get("recent_changes", "")
        fw = _cache.get("frameworks", "")
    if rc:
        lines.append(rc)
    if fw:
        lines.append(fw)

    return "\n".join(lines)


def _add_project_identity(store, project_root: str, lines: list[str]) -> None:
    root_name = Path(project_root).name
    lines.append(f"### {root_name}")
    lines.append("")
    entries = store.search_by_kind("module", limit=50)
    entries = [e for e in entries if e.file_path and e.file_path.startswith(project_root)]
    entries.sort(key=lambda e: e.line_count or 0, reverse=True)
    if entries:
        lines.append(f"**Key modules ({len(entries)} indexed):**")
        for e in entries[:10]:
            lc = f" [{e.line_count}L]" if e.line_count else ""
            summary = e.summary.split('\n')[0][:100]
            lines.append(f"- {e.symbol_name}{lc}: {summary}")
        lines.append("")


def _add_class_overview(store, project_root: str, lines: list[str]) -> None:
    """Show main classes — Redis-backed."""
    entries = store.search_by_kind("class", limit=50)
    entries = [e for e in entries if e.file_path and e.file_path.startswith(project_root)]
    entries.sort(key=lambda e: e.line_count or 0, reverse=True)
    if entries:
        lines.append("### Key Classes")
        lines.append("")
        for e in entries[:10]:
            rel = str(Path(e.file_path).relative_to(project_root)) if e.file_path.startswith(project_root) else e.file_path
            lines.append(f"- **{e.symbol_name}** ({rel})")
        lines.append("")


def _git_recent_changes(project_root: str) -> str:
    """Get recent git changes. Runs in background thread, safe to block."""
    try:
        result = subprocess.run(
            ["git", "log", "--since=7 days ago", "--name-only", "--pretty=format:", "--diff-filter=ACMR"],
            capture_output=True, text=True, cwd=project_root, timeout=5)
        if result.returncode == 0:
            files = list(dict.fromkeys(f.strip() for f in result.stdout.strip().split('\n') if f.strip()))
            if files:
                lines = ["### Recently Changed (last 7 days)", ""]
                for f in files[:10]:
                    lines.append(f"- {f}")
                lines.append("")
                return "\n".join(lines)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return ""
