"""
Project mental model generator for elephant-coder.

Generates a human-readable project overview from indexed memories
and the file link graph. Injected into Claude's context at session start.

Fully Redis-backed — no SQLite queries, avoids WAL contention on Windows.
"""

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("elephant-coder.mental_model")


def generate_mental_model(store, project_root: str) -> str:
    """Generate a project mental model from indexed memories + link graph."""
    lines = ["## Project Mental Model (auto-generated by elephant-coder)", ""]
    _add_project_identity(store, project_root, lines)
    _add_class_overview(store, project_root, lines)
    _add_recent_changes(project_root, lines)
    return "\n".join(lines)


def _add_project_identity(store, project_root: str, lines: list[str]) -> None:
    root_name = Path(project_root).name
    lines.append(f"### {root_name}")
    lines.append("")
    # Redis-backed search — no SQLite
    entries = store.search_by_kind("module", limit=50)
    entries = [e for e in entries if e.file_path and e.file_path.startswith(project_root)]
    entries.sort(key=lambda e: e.line_count or 0, reverse=True)
    if entries:
        lines.append(f"**Key modules ({len(entries)} indexed):**")
        for e in entries[:10]:
            lc = f" [{e.line_count}L]" if e.line_count else ""
            summary = e.summary.split('\n')[0][:100]
            lines.append(f"- {e.symbol_name}{lc}: {summary}")
        lines.append("")


def _add_class_overview(store, project_root: str, lines: list[str]) -> None:
    """Show main classes — Redis-backed, replaces SQLite hub file query."""
    entries = store.search_by_kind("class", limit=50)
    entries = [e for e in entries if e.file_path and e.file_path.startswith(project_root)]
    entries.sort(key=lambda e: e.line_count or 0, reverse=True)
    if entries:
        lines.append("### Key Classes")
        lines.append("")
        for e in entries[:10]:
            rel = str(Path(e.file_path).relative_to(project_root)) if e.file_path.startswith(project_root) else e.file_path
            lines.append(f"- **{e.symbol_name}** ({rel})")
        lines.append("")


def _add_recent_changes(project_root: str, lines: list[str]) -> None:
    try:
        result = subprocess.run(
            ["git", "log", "--since=7 days ago", "--name-only", "--pretty=format:", "--diff-filter=ACMR"],
            capture_output=True, text=True, cwd=project_root, timeout=5)
        if result.returncode == 0:
            files = list(dict.fromkeys(f.strip() for f in result.stdout.strip().split('\n') if f.strip()))
            if files:
                lines.append("### Recently Changed (last 7 days)")
                lines.append("")
                for f in files[:10]:
                    lines.append(f"- {f}")
                lines.append("")
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
