"""
Project mental model generator for elephant-coder.

Generates a human-readable project overview from indexed memories
and the file link graph. Injected into Claude's context at session start.
"""

import logging
import os
import subprocess
from pathlib import Path

logger = logging.getLogger("elephant-coder.mental_model")


def generate_mental_model(store, project_root: str) -> str:
    """Generate a project mental model from indexed memories + link graph."""
    lines = ["## Project Mental Model (auto-generated by elephant-coder)", ""]
    _add_project_identity(store, project_root, lines)
    _add_architecture(store, project_root, lines)
    _add_recent_changes(project_root, lines)
    _add_stats(store, lines)
    return "\n".join(lines)


def _add_project_identity(store, project_root: str, lines: list[str]) -> None:
    root_name = Path(project_root).name
    lines.append(f"### {root_name}")
    lines.append("")
    # Use Redis-backed search instead of raw SQLite to avoid WAL contention
    entries = store.search_by_kind("module", limit=10)
    # Filter to current project and sort by line count
    entries = [e for e in entries if e.file_path and e.file_path.startswith(project_root)]
    entries.sort(key=lambda e: e.line_count or 0, reverse=True)
    if entries:
        lines.append("**Key modules:**")
        for e in entries[:10]:
            lc = f" [{e.line_count}L]" if e.line_count else ""
            summary = e.summary.split('\n')[0][:100]
            lines.append(f"- {e.symbol_name}{lc}: {summary}")
        lines.append("")


def _add_architecture(store, project_root: str, lines: list[str]) -> None:
    try:
        hubs = store.get_hub_files(limit=10)
    except Exception:
        hubs = []
    if hubs:
        lines.append("### Most Connected Files (architectural pillars)")
        lines.append("")
        for hub in hubs:
            fp = hub["file_path"]
            rel = os.path.relpath(fp, project_root) if fp.startswith(project_root) else fp
            lines.append(f"- {rel} (imported by {hub['inbound_count']} files)")
        lines.append("")


def _add_recent_changes(project_root: str, lines: list[str]) -> None:
    try:
        result = subprocess.run(
            ["git", "log", "--since=7 days ago", "--name-only", "--pretty=format:", "--diff-filter=ACMR"],
            capture_output=True, text=True, cwd=project_root, timeout=5)
        if result.returncode == 0:
            files = list(dict.fromkeys(f.strip() for f in result.stdout.strip().split('\n') if f.strip()))
            if files:
                lines.append("### Recently Changed (last 7 days)")
                lines.append("")
                for f in files[:10]:
                    lines.append(f"- {f}")
                lines.append("")
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass


def _add_stats(store, lines: list[str]) -> None:
    total = store.count()
    lines.append(f"### Memory: {total}/{store.max_memories} entries indexed")
    lines.append("")
